_target_: nuplan.planning.simulation.observation.ml_planner_agents.MLPlannerAgents
_convert_: 'all'

model_config: ???  # Dictionary key from existing planner model config (e.g. reactive_agents_model)
checkpoint_path: ???  # Path to trained model checkpoint
