is_scenario_left_turn_tag_on_candidate_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.is_scenario_left_turn_tag_on_candidate.IsScenarioLeftTurnTagOnCandidateStatistics
  _convert_: 'all'
  name: 'is_scenario_left_turn_tag_on_candidate'
  category: 'Occlusions'
